port: 1892

Command to create ssh tunnel:
ssh -N -f -L 1892:argo-35:1892 gdolsten@argo-comp2.princeton.edu

Use a Browser on your local machine to go to:
localhost:1892  (prefix w/ https:// if using password)

[I 2024-05-11 16:49:40.608 ServerApp] Package notebook took 0.0000s to import
[I 2024-05-11 16:49:41.347 ServerApp] Package jupyter_lsp took 0.7377s to import
[W 2024-05-11 16:49:41.347 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2024-05-11 16:49:41.582 ServerApp] Package jupyter_server_terminals took 0.2344s to import
[I 2024-05-11 16:49:41.582 ServerApp] Package jupyterlab took 0.0000s to import
[W 2024-05-11 16:49:42.316 ServerApp] nbclassic | error adding extension (enabled: True): The module 'nbclassic' could not be found (No module named 'nbclassic'). Are you sure the extension is installed?
    Traceback (most recent call last):
      File "/Genomics/argo/users/gdolsten/.conda/envs/mamba/envs/scrna/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 321, in add_extension
        extpkg = ExtensionPackage(name=extension_name, enabled=enabled)
      File "/Genomics/argo/users/gdolsten/.conda/envs/mamba/envs/scrna/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 185, in __init__
        self._load_metadata()
      File "/Genomics/argo/users/gdolsten/.conda/envs/mamba/envs/scrna/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 200, in _load_metadata
        raise ExtensionModuleNotFound(msg) from None
    jupyter_server.extension.utils.ExtensionModuleNotFound: The module 'nbclassic' could not be found (No module named 'nbclassic'). Are you sure the extension is installed?
[I 2024-05-11 16:49:42.319 ServerApp] Package notebook_shim took 0.0000s to import
[W 2024-05-11 16:49:42.319 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2024-05-11 16:49:42.334 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-05-11 16:49:42.338 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2024-05-11 16:49:42.346 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-05-11 16:49:42.350 ServerApp] notebook | extension was successfully linked.
[I 2024-05-11 16:49:48.684 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-05-11 16:49:49.047 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-05-11 16:49:49.049 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-05-11 16:49:49.051 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-05-11 16:49:49.084 LabApp] JupyterLab extension loaded from /Genomics/argo/users/gdolsten/.conda/envs/mamba/envs/scrna/lib/python3.10/site-packages/jupyterlab
[I 2024-05-11 16:49:49.084 LabApp] JupyterLab application directory is /Genomics/argo/users/gdolsten/.conda/envs/mamba/envs/scrna/share/jupyter/lab
[I 2024-05-11 16:49:49.096 LabApp] Extension Manager is 'pypi'.
[I 2024-05-11 16:49:49.098 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-05-11 16:49:49.102 ServerApp] notebook | extension was successfully loaded.
[I 2024-05-11 16:49:49.102 ServerApp] Serving notebooks from local directory: /Genomics/pritykinlab/gabe/scTirFINAL/scTir1_Analysis
[I 2024-05-11 16:49:49.102 ServerApp] Jupyter Server 2.10.0 is running at:
[I 2024-05-11 16:49:49.102 ServerApp] http://argo-35:1892/tree?token=40c1601221e7b0f3c1410f24884056d483193930b0779ead
[I 2024-05-11 16:49:49.103 ServerApp]     http://127.0.0.1:1892/tree?token=40c1601221e7b0f3c1410f24884056d483193930b0779ead
[I 2024-05-11 16:49:49.103 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2024-05-11 16:49:49.127 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///Genomics/argo/users/gdolsten/.local/share/jupyter/runtime/jpserver-667536-open.html
    Or copy and paste one of these URLs:
        http://argo-35:1892/tree?token=40c1601221e7b0f3c1410f24884056d483193930b0779ead
        http://127.0.0.1:1892/tree?token=40c1601221e7b0f3c1410f24884056d483193930b0779ead
[I 2024-05-11 16:49:49.653 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[W 2024-05-11 16:51:03.976 ServerApp] 404 GET /notebook (@172.17.8.61) 146.01ms referer=None
[I 2024-05-11 16:51:07.498 ServerApp] 302 GET / (@172.17.8.61) 0.30ms
[I 2024-05-11 16:51:07.576 JupyterNotebookApp] 302 GET /tree? (@172.17.8.61) 0.40ms
[I 2024-05-11 16:51:18.373 ServerApp] User fdce7698dab14ae48b025018e88e7324 logged in.
[I 2024-05-11 16:51:18.373 ServerApp] 302 POST /login?next=%2Ftree%3F (fdce7698dab14ae48b025018e88e7324@172.17.8.61) 0.72ms
[W 2024-05-11 16:51:47.057 ServerApp] 500 GET /api/nbconvert?1715460706890 (172.17.8.61): Could not import nbconvert: No module named 'entrypoints'
[W 2024-05-11 16:51:47.057 ServerApp] wrote error: "Could not import nbconvert: No module named 'entrypoints'"
    Traceback (most recent call last):
      File "/Genomics/argo/users/gdolsten/.conda/envs/mamba/envs/scrna/lib/python3.10/site-packages/jupyter_server/services/nbconvert/handlers.py", line 34, in get
        from nbconvert.exporters import base
      File "/Genomics/argo/users/gdolsten/.local/lib/python3.10/site-packages/nbconvert/__init__.py", line 4, in <module>
        from .exporters import *
      File "/Genomics/argo/users/gdolsten/.local/lib/python3.10/site-packages/nbconvert/exporters/__init__.py", line 1, in <module>
        from .base import (export, get_exporter,
      File "/Genomics/argo/users/gdolsten/.local/lib/python3.10/site-packages/nbconvert/exporters/base.py", line 8, in <module>
        import entrypoints
    ModuleNotFoundError: No module named 'entrypoints'
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/Genomics/argo/users/gdolsten/.conda/envs/mamba/envs/scrna/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/Genomics/argo/users/gdolsten/.conda/envs/mamba/envs/scrna/lib/python3.10/site-packages/jupyter_server/services/nbconvert/handlers.py", line 36, in get
        raise web.HTTPError(500, "Could not import nbconvert: %s" % e) from e
    tornado.web.HTTPError: HTTP 500: Internal Server Error (Could not import nbconvert: No module named 'entrypoints')
[E 2024-05-11 16:51:47.132 ServerApp] {
      "Host": "localhost:1892",
      "Accept": "*/*",
      "Referer": "http://localhost:1892/tree?",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
    }
[E 2024-05-11 16:51:47.132 ServerApp] 500 GET /api/nbconvert?1715460706890 (fdce7698dab14ae48b025018e88e7324@172.17.8.61) 96.78ms referer=http://localhost:1892/tree?
[W 2024-05-11 16:51:49.601 ServerApp] 500 GET /api/nbconvert?1715460709534 (172.17.8.61): Could not import nbconvert: No module named 'entrypoints'
[W 2024-05-11 16:51:49.601 ServerApp] wrote error: "Could not import nbconvert: No module named 'entrypoints'"
    Traceback (most recent call last):
      File "/Genomics/argo/users/gdolsten/.conda/envs/mamba/envs/scrna/lib/python3.10/site-packages/jupyter_server/services/nbconvert/handlers.py", line 34, in get
        from nbconvert.exporters import base
      File "/Genomics/argo/users/gdolsten/.local/lib/python3.10/site-packages/nbconvert/__init__.py", line 4, in <module>
        from .exporters import *
      File "/Genomics/argo/users/gdolsten/.local/lib/python3.10/site-packages/nbconvert/exporters/__init__.py", line 1, in <module>
        from .base import (export, get_exporter,
      File "/Genomics/argo/users/gdolsten/.local/lib/python3.10/site-packages/nbconvert/exporters/base.py", line 8, in <module>
        import entrypoints
    ModuleNotFoundError: No module named 'entrypoints'
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/Genomics/argo/users/gdolsten/.conda/envs/mamba/envs/scrna/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/Genomics/argo/users/gdolsten/.conda/envs/mamba/envs/scrna/lib/python3.10/site-packages/jupyter_server/services/nbconvert/handlers.py", line 36, in get
        raise web.HTTPError(500, "Could not import nbconvert: %s" % e) from e
    tornado.web.HTTPError: HTTP 500: Internal Server Error (Could not import nbconvert: No module named 'entrypoints')
[E 2024-05-11 16:51:49.601 ServerApp] {
      "Host": "localhost:1892",
      "Accept": "*/*",
      "Referer": "http://localhost:1892/notebooks/scrna-filter-d0.ipynb",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
    }
[E 2024-05-11 16:51:49.601 ServerApp] 500 GET /api/nbconvert?1715460709534 (fdce7698dab14ae48b025018e88e7324@172.17.8.61) 2.39ms referer=http://localhost:1892/notebooks/scrna-filter-d0.ipynb
[I 2024-05-11 16:51:54.982 ServerApp] Kernel started: c282920f-4ca7-405a-8170-e53d3628c362
[I 2024-05-11 16:51:56.182 ServerApp] Connecting to kernel c282920f-4ca7-405a-8170-e53d3628c362.
[I 2024-05-11 16:53:54.492 ServerApp] Saving file at /scrna-filter-d0.ipynb
[I 2024-05-11 16:57:54.783 ServerApp] Saving file at /scrna-filter-d0.ipynb
[I 2024-05-11 16:59:55.289 ServerApp] Saving file at /scrna-filter-d0.ipynb
[I 2024-05-11 17:01:55.865 ServerApp] Saving file at /scrna-filter-d0.ipynb
[I 2024-05-11 17:02:17.191 ServerApp] Starting buffering for c282920f-4ca7-405a-8170-e53d3628c362:625ea3dc-bd51-4fde-8058-d14517d0d9ee
[I 2024-05-11 17:02:17.333 ServerApp] Connecting to kernel c282920f-4ca7-405a-8170-e53d3628c362.
[I 2024-05-11 17:02:17.333 ServerApp] Restoring connection for c282920f-4ca7-405a-8170-e53d3628c362:625ea3dc-bd51-4fde-8058-d14517d0d9ee
[W 2024-05-11 17:03:47.337 ServerApp] WebSocket ping timeout after 90004 ms.
[W 2024-05-11 17:03:47.465 ServerApp] 
[W 2024-05-11 17:03:47.466 ServerApp] 
[W 2024-05-11 17:03:47.466 ServerApp] 
[W 2024-05-11 17:03:47.467 ServerApp] 
[W 2024-05-11 17:03:47.467 ServerApp] 
[W 2024-05-11 17:03:47.758 ServerApp] 
[W 2024-05-11 17:03:48.071 ServerApp] 
[W 2024-05-11 17:03:48.071 ServerApp] 
[W 2024-05-11 17:03:48.072 ServerApp] 
[W 2024-05-11 17:03:48.072 ServerApp] 
[W 2024-05-11 17:03:48.073 ServerApp] 
[W 2024-05-11 17:03:48.436 ServerApp] 
[W 2024-05-11 17:03:48.437 ServerApp] 
[W 2024-05-11 17:03:48.438 ServerApp] 
[W 2024-05-11 17:03:48.438 ServerApp] 
[I 2024-05-11 17:03:52.340 ServerApp] Starting buffering for c282920f-4ca7-405a-8170-e53d3628c362:625ea3dc-bd51-4fde-8058-d14517d0d9ee
[W 2024-05-11 18:05:49.427 ServerApp] 500 GET /api/nbconvert?1715465149295 (172.17.8.61): Could not import nbconvert: No module named 'entrypoints'
[W 2024-05-11 18:05:49.427 ServerApp] wrote error: "Could not import nbconvert: No module named 'entrypoints'"
    Traceback (most recent call last):
      File "/Genomics/argo/users/gdolsten/.conda/envs/mamba/envs/scrna/lib/python3.10/site-packages/jupyter_server/services/nbconvert/handlers.py", line 34, in get
        from nbconvert.exporters import base
      File "/Genomics/argo/users/gdolsten/.local/lib/python3.10/site-packages/nbconvert/__init__.py", line 4, in <module>
        from .exporters import *
      File "/Genomics/argo/users/gdolsten/.local/lib/python3.10/site-packages/nbconvert/exporters/__init__.py", line 1, in <module>
        from .base import (export, get_exporter,
      File "/Genomics/argo/users/gdolsten/.local/lib/python3.10/site-packages/nbconvert/exporters/base.py", line 8, in <module>
        import entrypoints
    ModuleNotFoundError: No module named 'entrypoints'
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/Genomics/argo/users/gdolsten/.conda/envs/mamba/envs/scrna/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/Genomics/argo/users/gdolsten/.conda/envs/mamba/envs/scrna/lib/python3.10/site-packages/jupyter_server/services/nbconvert/handlers.py", line 36, in get
        raise web.HTTPError(500, "Could not import nbconvert: %s" % e) from e
    tornado.web.HTTPError: HTTP 500: Internal Server Error (Could not import nbconvert: No module named 'entrypoints')
[E 2024-05-11 18:05:49.431 ServerApp] {
      "Host": "localhost:1892",
      "Accept": "*/*",
      "Referer": "http://localhost:1892/notebooks/scrna-filter-d0.ipynb",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
    }
[E 2024-05-11 18:05:49.431 ServerApp] 500 GET /api/nbconvert?1715465149295 (fdce7698dab14ae48b025018e88e7324@172.17.8.61) 42.10ms referer=http://localhost:1892/notebooks/scrna-filter-d0.ipynb
[I 2024-05-11 18:05:50.274 ServerApp] Connecting to kernel c282920f-4ca7-405a-8170-e53d3628c362.
[I 2024-05-11 18:05:50.275 ServerApp] Discarding 67 buffered messages for c282920f-4ca7-405a-8170-e53d3628c362:625ea3dc-bd51-4fde-8058-d14517d0d9ee
[I 2024-05-11 18:07:51.047 ServerApp] Saving file at /scrna-filter-d0.ipynb
[I 2024-05-11 18:09:54.418 ServerApp] Saving file at /scrna-filter-d0.ipynb
[W 2024-05-11 18:13:20.281 ServerApp] WebSocket ping timeout after 117342 ms.
[I 2024-05-11 18:13:25.284 ServerApp] Starting buffering for c282920f-4ca7-405a-8170-e53d3628c362:2649ab77-3e76-4407-be55-1890e241d5d4
[I 2024-05-11 18:13:58.197 ServerApp] Connecting to kernel c282920f-4ca7-405a-8170-e53d3628c362.
[I 2024-05-11 18:13:58.197 ServerApp] Restoring connection for c282920f-4ca7-405a-8170-e53d3628c362:2649ab77-3e76-4407-be55-1890e241d5d4
[I 2024-05-11 18:21:55.853 ServerApp] Saving file at /scrna-filter-d0.ipynb
[I 2024-05-11 18:25:58.034 ServerApp] Saving file at /scrna-filter-d0.ipynb
[I 2024-05-11 18:28:01.752 ServerApp] Saving file at /scrna-filter-d0.ipynb
[I 2024-05-11 18:50:08.812 ServerApp] Saving file at /scrna-filter-d0.ipynb
[W 2024-05-11 18:52:04.357 ServerApp] 500 GET /api/nbconvert?1715467923614 (172.17.8.61): Could not import nbconvert: No module named 'entrypoints'
[W 2024-05-11 18:52:04.358 ServerApp] wrote error: "Could not import nbconvert: No module named 'entrypoints'"
    Traceback (most recent call last):
      File "/Genomics/argo/users/gdolsten/.conda/envs/mamba/envs/scrna/lib/python3.10/site-packages/jupyter_server/services/nbconvert/handlers.py", line 34, in get
        from nbconvert.exporters import base
      File "/Genomics/argo/users/gdolsten/.local/lib/python3.10/site-packages/nbconvert/__init__.py", line 4, in <module>
        from .exporters import *
      File "/Genomics/argo/users/gdolsten/.local/lib/python3.10/site-packages/nbconvert/exporters/__init__.py", line 1, in <module>
        from .base import (export, get_exporter,
      File "/Genomics/argo/users/gdolsten/.local/lib/python3.10/site-packages/nbconvert/exporters/base.py", line 8, in <module>
        import entrypoints
    ModuleNotFoundError: No module named 'entrypoints'
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/Genomics/argo/users/gdolsten/.conda/envs/mamba/envs/scrna/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/Genomics/argo/users/gdolsten/.conda/envs/mamba/envs/scrna/lib/python3.10/site-packages/jupyter_server/services/nbconvert/handlers.py", line 36, in get
        raise web.HTTPError(500, "Could not import nbconvert: %s" % e) from e
    tornado.web.HTTPError: HTTP 500: Internal Server Error (Could not import nbconvert: No module named 'entrypoints')
[E 2024-05-11 18:52:04.358 ServerApp] {
      "Host": "localhost:1892",
      "Accept": "*/*",
      "Referer": "http://localhost:1892/notebooks/scrna-postfilter.ipynb",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
    }
[E 2024-05-11 18:52:04.358 ServerApp] 500 GET /api/nbconvert?1715467923614 (fdce7698dab14ae48b025018e88e7324@172.17.8.61) 25.83ms referer=http://localhost:1892/notebooks/scrna-postfilter.ipynb
[I 2024-05-11 18:52:08.241 ServerApp] Kernel started: 5ce75081-1ac3-443e-b663-9a51b865d5dc
[I 2024-05-11 18:52:09.001 ServerApp] Saving file at /scrna-filter-d0.ipynb
[I 2024-05-11 18:52:15.656 ServerApp] Kernel restarted: c282920f-4ca7-405a-8170-e53d3628c362
[I 2024-05-11 18:52:15.812 ServerApp] Starting buffering for c282920f-4ca7-405a-8170-e53d3628c362:2649ab77-3e76-4407-be55-1890e241d5d4
[I 2024-05-11 18:52:23.256 ServerApp] Connecting to kernel 5ce75081-1ac3-443e-b663-9a51b865d5dc.
[I 2024-05-11 18:52:23.401 ServerApp] Connecting to kernel c282920f-4ca7-405a-8170-e53d3628c362.
[I 2024-05-11 18:52:23.401 ServerApp] Restoring connection for c282920f-4ca7-405a-8170-e53d3628c362:2649ab77-3e76-4407-be55-1890e241d5d4
[I 2024-05-11 18:52:23.406 ServerApp] Replaying 3 buffered messages
[I 2024-05-11 18:54:09.352 ServerApp] Saving file at /scrna-filter-d0.ipynb
[I 2024-05-11 18:56:10.779 ServerApp] Saving file at /scrna-filter-d0.ipynb
[I 2024-05-11 18:56:13.951 ServerApp] Saving file at /scrna-postfilter.ipynb
[I 2024-05-11 18:58:12.378 ServerApp] Saving file at /scrna-filter-d0.ipynb
[I 2024-05-11 19:00:15.582 ServerApp] Saving file at /scrna-filter-d0.ipynb
[I 2024-05-11 19:02:19.292 ServerApp] Saving file at /scrna-filter-d0.ipynb
[I 2024-05-11 19:27:45.827 ServerApp] Starting buffering for c282920f-4ca7-405a-8170-e53d3628c362:2649ab77-3e76-4407-be55-1890e241d5d4
[I 2024-05-11 19:27:45.851 ServerApp] Starting buffering for 5ce75081-1ac3-443e-b663-9a51b865d5dc:cb5eddc7-de44-46f6-84bb-43fc7f7658fb
[I 2024-05-11 19:27:45.988 ServerApp] Connecting to kernel c282920f-4ca7-405a-8170-e53d3628c362.
[I 2024-05-11 19:27:45.988 ServerApp] Restoring connection for c282920f-4ca7-405a-8170-e53d3628c362:2649ab77-3e76-4407-be55-1890e241d5d4
[W 2024-05-11 19:29:15.991 ServerApp] WebSocket ping timeout after 90002 ms.
[I 2024-05-11 19:29:20.996 ServerApp] Starting buffering for c282920f-4ca7-405a-8170-e53d3628c362:2649ab77-3e76-4407-be55-1890e241d5d4
[I 2024-05-11 19:43:11.524 ServerApp] Connecting to kernel 5ce75081-1ac3-443e-b663-9a51b865d5dc.
[I 2024-05-11 19:43:11.524 ServerApp] Restoring connection for 5ce75081-1ac3-443e-b663-9a51b865d5dc:cb5eddc7-de44-46f6-84bb-43fc7f7658fb
[I 2024-05-11 19:43:11.571 ServerApp] Starting buffering for 5ce75081-1ac3-443e-b663-9a51b865d5dc:cb5eddc7-de44-46f6-84bb-43fc7f7658fb
[I 2024-05-12 01:42:35.824 ServerApp] 302 GET / (@172.17.8.61) 0.51ms
[I 2024-05-12 01:42:35.862 JupyterNotebookApp] 302 GET /tree? (@172.17.8.61) 0.33ms
[I 2024-05-12 01:42:59.395 ServerApp] User ee17b0ff00ea4b31a261009ac88986f7 logged in.
[I 2024-05-12 01:42:59.395 ServerApp] 302 POST /login?next=%2Ftree%3F (ee17b0ff00ea4b31a261009ac88986f7@172.17.8.61) 1.07ms
[W 2024-05-12 01:43:12.714 ServerApp] 500 GET /api/nbconvert?1715492592596 (172.17.8.61): Could not import nbconvert: No module named 'entrypoints'
[W 2024-05-12 01:43:12.714 ServerApp] wrote error: "Could not import nbconvert: No module named 'entrypoints'"
    Traceback (most recent call last):
      File "/Genomics/argo/users/gdolsten/.conda/envs/mamba/envs/scrna/lib/python3.10/site-packages/jupyter_server/services/nbconvert/handlers.py", line 34, in get
        from nbconvert.exporters import base
      File "/Genomics/argo/users/gdolsten/.local/lib/python3.10/site-packages/nbconvert/__init__.py", line 4, in <module>
        from .exporters import *
      File "/Genomics/argo/users/gdolsten/.local/lib/python3.10/site-packages/nbconvert/exporters/__init__.py", line 1, in <module>
        from .base import (export, get_exporter,
      File "/Genomics/argo/users/gdolsten/.local/lib/python3.10/site-packages/nbconvert/exporters/base.py", line 8, in <module>
        import entrypoints
    ModuleNotFoundError: No module named 'entrypoints'
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/Genomics/argo/users/gdolsten/.conda/envs/mamba/envs/scrna/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/Genomics/argo/users/gdolsten/.conda/envs/mamba/envs/scrna/lib/python3.10/site-packages/jupyter_server/services/nbconvert/handlers.py", line 36, in get
        raise web.HTTPError(500, "Could not import nbconvert: %s" % e) from e
    tornado.web.HTTPError: HTTP 500: Internal Server Error (Could not import nbconvert: No module named 'entrypoints')
[E 2024-05-12 01:43:12.718 ServerApp] {
      "Host": "localhost:1892",
      "Accept": "*/*",
      "Referer": "http://localhost:1892/tree?",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
    }
[E 2024-05-12 01:43:12.718 ServerApp] 500 GET /api/nbconvert?1715492592596 (ee17b0ff00ea4b31a261009ac88986f7@172.17.8.61) 42.95ms referer=http://localhost:1892/tree?
[W 2024-05-12 01:43:15.116 ServerApp] 500 GET /api/nbconvert?1715492595037 (172.17.8.61): Could not import nbconvert: No module named 'entrypoints'
[W 2024-05-12 01:43:15.116 ServerApp] wrote error: "Could not import nbconvert: No module named 'entrypoints'"
    Traceback (most recent call last):
      File "/Genomics/argo/users/gdolsten/.conda/envs/mamba/envs/scrna/lib/python3.10/site-packages/jupyter_server/services/nbconvert/handlers.py", line 34, in get
        from nbconvert.exporters import base
      File "/Genomics/argo/users/gdolsten/.local/lib/python3.10/site-packages/nbconvert/__init__.py", line 4, in <module>
        from .exporters import *
      File "/Genomics/argo/users/gdolsten/.local/lib/python3.10/site-packages/nbconvert/exporters/__init__.py", line 1, in <module>
        from .base import (export, get_exporter,
      File "/Genomics/argo/users/gdolsten/.local/lib/python3.10/site-packages/nbconvert/exporters/base.py", line 8, in <module>
        import entrypoints
    ModuleNotFoundError: No module named 'entrypoints'
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/Genomics/argo/users/gdolsten/.conda/envs/mamba/envs/scrna/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/Genomics/argo/users/gdolsten/.conda/envs/mamba/envs/scrna/lib/python3.10/site-packages/jupyter_server/services/nbconvert/handlers.py", line 36, in get
        raise web.HTTPError(500, "Could not import nbconvert: %s" % e) from e
    tornado.web.HTTPError: HTTP 500: Internal Server Error (Could not import nbconvert: No module named 'entrypoints')
[E 2024-05-12 01:43:15.117 ServerApp] {
      "Host": "localhost:1892",
      "Accept": "*/*",
      "Referer": "http://localhost:1892/notebooks/scrna-postfilter.ipynb",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
    }
[E 2024-05-12 01:43:15.117 ServerApp] 500 GET /api/nbconvert?1715492595037 (ee17b0ff00ea4b31a261009ac88986f7@172.17.8.61) 1.50ms referer=http://localhost:1892/notebooks/scrna-postfilter.ipynb
[I 2024-05-12 01:43:16.778 ServerApp] Connecting to kernel 5ce75081-1ac3-443e-b663-9a51b865d5dc.
[W 2024-05-12 01:43:17.101 ServerApp] 500 GET /api/nbconvert?1715492597021 (172.17.8.61): Could not import nbconvert: No module named 'entrypoints'
[W 2024-05-12 01:43:17.101 ServerApp] wrote error: "Could not import nbconvert: No module named 'entrypoints'"
    Traceback (most recent call last):
      File "/Genomics/argo/users/gdolsten/.conda/envs/mamba/envs/scrna/lib/python3.10/site-packages/jupyter_server/services/nbconvert/handlers.py", line 34, in get
        from nbconvert.exporters import base
      File "/Genomics/argo/users/gdolsten/.local/lib/python3.10/site-packages/nbconvert/__init__.py", line 4, in <module>
        from .exporters import *
      File "/Genomics/argo/users/gdolsten/.local/lib/python3.10/site-packages/nbconvert/exporters/__init__.py", line 1, in <module>
        from .base import (export, get_exporter,
      File "/Genomics/argo/users/gdolsten/.local/lib/python3.10/site-packages/nbconvert/exporters/base.py", line 8, in <module>
        import entrypoints
    ModuleNotFoundError: No module named 'entrypoints'
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/Genomics/argo/users/gdolsten/.conda/envs/mamba/envs/scrna/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/Genomics/argo/users/gdolsten/.conda/envs/mamba/envs/scrna/lib/python3.10/site-packages/jupyter_server/services/nbconvert/handlers.py", line 36, in get
        raise web.HTTPError(500, "Could not import nbconvert: %s" % e) from e
    tornado.web.HTTPError: HTTP 500: Internal Server Error (Could not import nbconvert: No module named 'entrypoints')
[E 2024-05-12 01:43:17.101 ServerApp] {
      "Host": "localhost:1892",
      "Accept": "*/*",
      "Referer": "http://localhost:1892/notebooks/final-figures.ipynb",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
    }
[E 2024-05-12 01:43:17.101 ServerApp] 500 GET /api/nbconvert?1715492597021 (ee17b0ff00ea4b31a261009ac88986f7@172.17.8.61) 1.49ms referer=http://localhost:1892/notebooks/final-figures.ipynb
[I 2024-05-12 01:43:17.710 ServerApp] Kernel started: 5486b953-7a23-4ffb-924a-84b3c00de7aa
[I 2024-05-12 01:43:34.850 ServerApp] Connecting to kernel 5486b953-7a23-4ffb-924a-84b3c00de7aa.
[W 2024-05-12 01:44:00.148 ServerApp] 500 GET /api/nbconvert?1715492640066 (172.17.8.61): Could not import nbconvert: No module named 'entrypoints'
[W 2024-05-12 01:44:00.148 ServerApp] wrote error: "Could not import nbconvert: No module named 'entrypoints'"
    Traceback (most recent call last):
      File "/Genomics/argo/users/gdolsten/.conda/envs/mamba/envs/scrna/lib/python3.10/site-packages/jupyter_server/services/nbconvert/handlers.py", line 34, in get
        from nbconvert.exporters import base
      File "/Genomics/argo/users/gdolsten/.local/lib/python3.10/site-packages/nbconvert/__init__.py", line 4, in <module>
        from .exporters import *
      File "/Genomics/argo/users/gdolsten/.local/lib/python3.10/site-packages/nbconvert/exporters/__init__.py", line 1, in <module>
        from .base import (export, get_exporter,
      File "/Genomics/argo/users/gdolsten/.local/lib/python3.10/site-packages/nbconvert/exporters/base.py", line 8, in <module>
        import entrypoints
    ModuleNotFoundError: No module named 'entrypoints'
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/Genomics/argo/users/gdolsten/.conda/envs/mamba/envs/scrna/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/Genomics/argo/users/gdolsten/.conda/envs/mamba/envs/scrna/lib/python3.10/site-packages/jupyter_server/services/nbconvert/handlers.py", line 36, in get
        raise web.HTTPError(500, "Could not import nbconvert: %s" % e) from e
    tornado.web.HTTPError: HTTP 500: Internal Server Error (Could not import nbconvert: No module named 'entrypoints')
[E 2024-05-12 01:44:00.148 ServerApp] {
      "Host": "localhost:1892",
      "Accept": "*/*",
      "Referer": "http://localhost:1892/notebooks/scrna-filter-d0.ipynb",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
    }
[E 2024-05-12 01:44:00.148 ServerApp] 500 GET /api/nbconvert?1715492640066 (ee17b0ff00ea4b31a261009ac88986f7@172.17.8.61) 2.11ms referer=http://localhost:1892/notebooks/scrna-filter-d0.ipynb
[I 2024-05-12 01:44:02.739 ServerApp] Connecting to kernel c282920f-4ca7-405a-8170-e53d3628c362.
[I 2024-05-12 01:45:19.965 ServerApp] Saving file at /scrna-postfilter.ipynb
[I 2024-05-12 01:45:20.939 ServerApp] Saving file at /final-figures.ipynb
[W 2024-05-12 01:45:21.064 ServerApp] /Genomics/pritykinlab/gabe/scTirFINAL/scTir1_Analysis/.~final-figures.ipynb doesn't exist
[I 2024-05-12 01:46:05.323 ServerApp] Saving file at /scrna-filter-d0.ipynb
[I 2024-05-12 01:47:26.026 ServerApp] Saving file at /scrna-postfilter.ipynb
[I 2024-05-12 01:49:24.001 ServerApp] Saving file at /final-figures.ipynb
[W 2024-05-12 01:49:24.130 ServerApp] /Genomics/pritykinlab/gabe/scTirFINAL/scTir1_Analysis/.~final-figures.ipynb doesn't exist
[I 2024-05-12 01:49:29.612 ServerApp] Saving file at /scrna-postfilter.ipynb
[I 2024-05-12 01:51:26.179 ServerApp] Saving file at /final-figures.ipynb
[I 2024-05-12 01:53:29.631 ServerApp] Saving file at /final-figures.ipynb
[I 2024-05-12 01:55:31.909 ServerApp] Saving file at /final-figures.ipynb
[I 2024-05-12 01:57:34.179 ServerApp] Saving file at /final-figures.ipynb
[I 2024-05-12 01:59:36.213 ServerApp] Saving file at /final-figures.ipynb
[I 2024-05-12 02:01:38.444 ServerApp] Saving file at /final-figures.ipynb
[I 2024-05-12 02:03:40.664 ServerApp] Saving file at /final-figures.ipynb
[I 2024-05-12 02:05:30.027 ServerApp] Saving file at /final-figures.ipynb
[I 2024-05-12 02:07:12.494 ServerApp] Kernel restarted: 5486b953-7a23-4ffb-924a-84b3c00de7aa
[I 2024-05-12 02:07:12.533 ServerApp] Starting buffering for 5486b953-7a23-4ffb-924a-84b3c00de7aa:4dcf7d85-25c0-4269-b358-727aa0f23e48
[I 2024-05-12 02:07:12.590 ServerApp] Connecting to kernel 5486b953-7a23-4ffb-924a-84b3c00de7aa.
[I 2024-05-12 02:07:12.590 ServerApp] Restoring connection for 5486b953-7a23-4ffb-924a-84b3c00de7aa:4dcf7d85-25c0-4269-b358-727aa0f23e48
[I 2024-05-12 02:07:30.296 ServerApp] Saving file at /final-figures.ipynb
[I 2024-05-12 02:09:32.697 ServerApp] Saving file at /final-figures.ipynb
[I 2024-05-12 02:11:35.108 ServerApp] Saving file at /final-figures.ipynb
